-- Write your migrate up statements here
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS
	secrets (
		id TEXT PRIMARY KEY NOT NULL,
		VALUE TEXT NOT NULL,
		created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
	);

CREATE TABLE IF NOT EXISTS
	users (
		id TEXT PRIMARY KEY NOT NULL,
		NAME TEXT NOT NULL,
		email CITEXT NOT NULL,
		email_verified BOOLEAN NOT NULL DEFAULT FALSE,
		email_verification_token TEXT NOT NULL DEFAULT ''::TEXT,
		email_verification_token_expiry TIMESTAMPTZ,
		PASSWORD TEXT NOT NULL,
		password_reset_token TEXT NOT NULL DEFAULT ''::TEXT,
		password_reset_correlation_token TEXT NOT NULL DEFAULT ''::TEXT,
		password_reset_token_expiry TIMESTAMPTZ,
		bio TEXT NOT NULL DEFAULT ''::TEXT,
		ROLE TEXT NOT NULL DEFAULT 'user'::TEXT,
		recent_login_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		CONSTRAINT users_unique_email UNIQUE (email)
	);

CREATE TABLE IF NOT EXISTS
	viewsets (
		id TEXT PRIMARY KEY NOT NULL,
		NAME TEXT NOT NULL,
		TYPE TEXT NOT NULL DEFAULT 'private'::TEXT,
		description TEXT NOT NULL DEFAULT '',
		is_starred BOOLEAN NOT NULL DEFAULT FALSE,
		starred_at TIMESTAMPTZ,
		accessed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		is_archived BOOLEAN NOT NULL DEFAULT FALSE,
		archived_at TIMESTAMPTZ,
		user_id TEXT NOT NULL,
		created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		CONSTRAINT viewsets_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS
	VIEWS (
		id TEXT PRIMARY KEY NOT NULL,
		NAME TEXT NOT NULL,
		TYPE TEXT NOT NULL,
		viewset_id TEXT,
		code TEXT NOT NULL DEFAULT '',
		HEIGHT TEXT NOT NULL,
		WIDTH TEXT NOT NULL,
		INDEX SMALLINT NOT NULL DEFAULT 0,
		is_main BOOLEAN NOT NULL DEFAULT FALSE,
		user_id TEXT NOT NULL,
		created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		CONSTRAINT views_viewset_id_fk FOREIGN KEY (viewset_id) REFERENCES viewsets (id) ON DELETE CASCADE,
		CONSTRAINT views_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
	);

---- create above / drop below ----
DROP TABLE IF EXISTS VIEWS;

DROP TABLE IF EXISTS viewsets;

DROP TABLE IF EXISTS secrets;

DROP TABLE IF EXISTS users;

DROP EXTENSION IF EXISTS citext;